### ISSUE TITLE
Swift Package Manager: nanopb deployment target warning

### ISSUE THREAD

**Issue by canbalkaya** [AgoraIO/AgoraRtcEngine_iOS#14]
Environment

Xcode version: Xcode 13.1
SDK version: 3.0.0
Installation method: Swift Package Manager
Problem

This dependency shows the following warning in Xcode 13.1 when integrating AgoraRtcKit using Swift Package Manager:

`The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99.`

<img width="495" alt="Screen Shot 2022-02-09 at 10 00 01 01PM" src="https://user-images.githubusercontent.com/18351145/153271230-e94318d7-2480-4255-badb-fc8f50cfa3e9.png">

**Comment by maxxfrazer** [comment]
Hi Can, the easiest solution is to use a newer version of the SDK. For example [`3.6.1-r.2`](https://github.com/AgoraIO/AgoraRtcEngine_iOS/releases/tag/3.6.1-r.2), which should be treated as a hotfix of 3.6.1.
Otherwise 3.6.2 will fix this warning. However the warning has no effect on the library, just its minimum required iOS is very low.

**Comment by canbalkaya** [comment]
Hi Max. Thanks.
