### ISSUE TITLE
Doesn't compile on M1 Macs with a target for simulator

### ISSUE THREAD

**Issue by kylebrowning** [AgoraIO/AgoraRtcEngine_iOS#2]
Title says it all.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AgoraRtcAudioVolumeInfo", referenced from:
      objc-class-ref in LiveRoom+Extension.o
  "_OBJC_CLASS_$_AgoraRtcEngineKit", referenced from:
      objc-class-ref in AgoraManager.o
ld: symbol(s) not found for architecture arm64

**Comment by yoreland** [comment]
from 3.4.5 sdk is partially supported, you could check:

https://docs.agora.io/en/Interactive%20Broadcast/release_ios_video?platform=iOS

2. App running on an M1 Mac

This release supports running apps that integrate the Agora iOS SDK on a physical M1 Mac. Due to hardware differences between M1 Mac, iPhone, and iPad, the Agora iOS SDK does not support iPhone- and iPad-specific hardware behaviors on an M1 Mac. For example, it does not support switching the audio route to the earpiece and does not support a rear camera.

**Comment by kylebrowning** [comment]
We're not trying to use an iPhone app on an M1. 

We're trying to compile an iPhone app to a simulator on an M1. 

The binaries supplied this in package do have not been compiled for arm64, specifically an M1 Mac. 

Compiling to a simulator on an x86 machine (intel) works fine.

**Comment by maxxfrazer** [comment]
Currently only physical devices and "Any iOS Device" options are supported on M1 Macs

This should be fixed in the next release, and if not then please report a ticket on https://agora-ticket.agora.io/

**Comment by kylebrowning** [comment]
Looking forward to it. Any release timetable?

**Comment by maxxfrazer** [comment]
@kylebrowning I've been told "next Monday", tbc if that means the 12th or 19th

**Comment by kylebrowning** [comment]
@maxxfrazer thanks, I won't hold you to it, was just trying judge if it was months away or not.

**Comment by kylebrowning** [comment]
Just as a heads up, this also breaks SwiftUI previews in the canvas making editing SwiftUI on the fly virtually impossible.

**Comment by maxxfrazer** [comment]
@kylebrowning I just checked 3.4.6 (just released), it builds fine with this package on M1 simulator 🚀

**Comment by zhigang1992** [comment]
This is great news! We can finally start using m1 for detox e2e tests

**Comment by zhigang1992** [comment]
@maxxfrazer 

It's seems like AgoraAIDenoiseExtension still doesn't compile on M1 simulators, it's included in AgoraRtcEngine. And I'm not sure how to disable it.

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/kylefang/Playground/testm1expo/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64
```

**Comment by maxxfrazer** [comment]
@zhigang1992 you're building the cocoapod, this repo is for the Swift Package integration that is now working as of 3.4.6. The SDK team is having problems publishing the XCFramework version to cocoapods so the M1 simulator version is only working with the Swift Package Manager integration since 3.4.6:
![Screen Shot 2021-07-16 at 10 15 05](https://user-images.githubusercontent.com/5754073/125924399-9f57fe27-77dd-4a6e-b99c-e27be850c592.png)
