### ISSUE TITLE
AgoraErrorCodeNoPermission no longer getting called

### ISSUE THREAD

**Issue by jonah-katz** [AgoraIO/AgoraRtcEngine_iOS#29]
`rtcEngine(_ engine: AgoraRtcEngineKit, didOccurError` used to be reported with `AgoraErrorCodeNoPermission`, but since I updated recently, that error no longer occurs.

**Comment by maxxfrazer** [comment]
just to check, it's no longer being called when it should for you @jonah-katz? I checked the docs and can't see anything about it being removed.

This repo is more for distribution of the SDK, rather than issue with it, to get to the SDK team the best route is hitting the support button on the console. It will lead you to here: https://agora-ticket.agora.io
Be sure to tell them all relevant information, including the SDK version you're having this issue with, as well as device OS. Cam/mic permissions on Apple devices have changed in the past with OS updates.

**Comment by maxxfrazer** [comment]
@jonah-katz there is a separate method, `rtcEngine(_ engine:, permissionError type:)`, which might be what you're looking for.

**Comment by jonah-katz** [comment]
That worked, thanks. I'll report the origin bug as well.
