### ISSUE TITLE
How can I use Agora to implement Picture in Picture function on the iOS platform?

### ISSUE THREAD

**Issue by yanyin1986** [AgoraIO/AgoraRtcEngine_iOS#30]
According to the iOS PIP document, I try to draw the CVPixelBuffer on AVSampleBufferLayer to set PIP up.
by this function I did make the remote view displayed on the AVSampleBufferLayer on the foreground mode.
```objective-c
- (void)setRemoteVideoRenderer:(id<AgoraVideoSinkProtocol> _Nullable)videoRenderer forUserId:(NSUInteger)userId;
```
When I swap the app into background mode, I could hear the audio but can't get the CVPixelBuffer by:
```swift
# AgoraVideoSinkProtocol

func renderPixelBuffer(_ pixelBuffer: CVPixelBuffer, rotation: AgoraVideoRotation) {}
```
Is there anyway to get CVPixelBuffer on the background mode?

**Comment by maxxfrazer** [comment]
This is a pretty hard feature to pull off, especially as I think there's not a way to have this for multiple remote users - that's why you don't see it in WhatsApp yet for example
We have an example inside the [API-Examples](https://github.com/AgoraIO/API-Examples/tree/main/iOS/APIExample/APIExample/Examples/Advanced/PictureInPicture) project that does it; that's a good place to start.

**Comment by maxxfrazer** [comment]
What version are you using @yanyin1986? I believe one of the patch updates a few months ago in 3.x made the CVPixelBuffer work in background mode when we saw it wasn't working for this exact use-case. @plutoless might know, as he's the brains behind API-Examples.

**Comment by yanyin1986** [comment]
@maxxfrazer 
The SDK version we are using is `3.4.7.3`.
OK I will check the API-Examples, Thanks a lot. 😄

**Comment by maxxfrazer** [comment]
I think the patch was at least in the 3.6.x versions, so you'll for sure need to update from 3.4

**Comment by maxxfrazer** [comment]
Looks like this is sorted, closing issue!
