### ISSUE TITLE
How to set video capture device?

### ISSUE THREAD

**Issue by WestFlow127** [AgoraIO/AgoraRtcEngine_iOS#31]
I want the RtcEngine to use the `AVCaptureDevice.DeviceType.builtInUltraWideCamera` when streaming video to the user.
I noticed the [AgoraVideoViewer](https://agoraio-community.github.io/VideoUIKit-iOS/documentation/agorauikit/agoravideoviewer/setcapturedevice(to:)/) SDK has this ability.

How do I accomplish this with the AgoraRtcEngine?

**Comment by maxxfrazer** [comment]
Hi @WestFlow127, I'm glad you saw that in Video UI Kit!

A recent sample project does show this with just the SDK:
https://github.com/AgoraIO-Community/RTC-Custom-Camera

The reason it was added to Video UI Kit is because IMO it's a bit long with just the SDK, but if you take this class from UI Kit it should help a bit with implementation:

https://github.com/AgoraIO-Community/VideoUIKit-iOS/pull/83/files#diff-5103c182a7d5b5869218fdf942d2c34de0e04e300d05f16e79b84177eebdbb38

**Comment by WestFlow127** [comment]
Okay, this is helpful! Thank you.
