### ISSUE TITLE
[INTEGRATION]

### ISSUE THREAD

**Issue by DioGnDev** [AgoraIO/AgoraRtcEngine_iOS#49]
**Describe the bug**
impact for all of my unit test, no such module AgoraRtcKit

**To Reproduce**
1. add  .package(
      url: "https://github.com/AgoraIO/AgoraRtcEngine_iOS",
      exact: "4.2.2"
    ) to SPM Module
2. target dependencies: [ .product(name: "RtcBasic", package: "AgoraRtcEngine_iOS") ]
3. Just run common unit test
 ```
Referenced from: <C4BD9BAA-6BCD-3BD0-B571-F26D7B9A8DAC> /Users/diiyo/Library/Developer/Xcode/DerivedData/Perqara-cnhuypusaxncxcborxzzqcvcvuag/Build/Products/Debug-iphonesimulator/AthenaiOSTests.xctest/AthenaiOSTests
  Reason: tried: '/Users/diiyo/Library/Developer/Xcode/DerivedData/Perqara-cnhuypusaxncxcborxzzqcvcvuag/Build/Products/Debug-iphonesimulator/AgoraRtcKit.framework/AgoraRtcKit' (code signature in <1E33CDC3-97F3-3750-8053-8705789E9E2E> '/Users/diiyo/Library/Developer/Xcode/DerivedData/Perqara-cnhuypusaxncxcborxzzqcvcvuag/Build/Products/Debug-iphonesimulator/AgoraRtcKit.framework/AgoraRtcKit' not valid for use in process: Trying to load an unsigned library), '/Users/diiyo/Library/Developer/Xcode/DerivedData/Perqara-cnhuypusaxncxcborxzzqcvcvuag/Build/Products/Debug-iphonesimulator/PackageFrameworks/AgoraRtcKit.framework/AgoraRtcKit' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/AgoraRtcKit.framework/AgoraRtcKit' (no such file)
 ```

**Comment by maxxfrazer** [comment]
@DioGnDev this seems very similar to an issue other developers are having when including XCFramework packages, only with the modular configurations. When you import the SDK in the xcodeproject the other way the issue does not persist:
#13 
https://github.com/AgoraIO/AgoraRtcEngine_iOS/issues/13#issuecomment-1709580655

https://developer.apple.com/forums/thread/651343?answerId=757417022#757417022

There doesn't seem to be anything we can do but use the other import methods, or bother Apple until it's fixed in Xcode.

**Comment by DioGnDev** [comment]
Thank you for your response Mr. Maxx
